- system/argocd/argocd-values.yaml
Mise à jour des permissions dans argo pour l'équipe SRE qui permet de supprimer et créer des repertoires avec ArgoCD.
Users were unable to delete pods
n/a
> update rbac permissions for operators of argoCD

- system/argocd/kustomization.yaml
> argocd sync

- system/grafana/helm/grafana-values.yaml
SSO auth with github for grafana
not tested yet
na
> adds sso for grafana

- system/vault/helm/vault.values.yaml
- terraform/vault/override-values.yml.tmpl
> changed vault plugins path

- system/vault/configs/gh-secret-engine.yaml
- system/vault/configs/kv-secret-engine.yaml
- system/vault/configs/policies.yaml
> vault github connection [test]

- apps/argo-apps/kustomization.yaml
- secret-px-deploy-key.yaml
- system/pixie/helm/pixie-helm-application.yaml
- system/pixie/helm/values.yaml
- system/pixie/kustomization.yaml
- system/pixie/resources/.gitignore
- system/pixie/resources/namespace-pl.yaml
Install Pixie with the Helm chart.
Newrelic hosted Pixie-cloud is used.
#76
> Add pixie helm argo app

- apps/samples/opentelemetry-demo/staging/helm/otel-demo-values.yaml
Send otel traces, metrics and logs to clickhouse db
- Closes #63 
See grafana dashboard
> Connected otel-demo with clickhouse (traces, metrics and logs)

- system/pixie/helm/pixie-helm-application.yaml
Hotfix on pixie to change sync mode.
> Hotfix on pixie to change sync mode.

- system/pixie/helm/pixie-helm-application.yaml
> hotfix pixie argo create namespace priv.

- system/vault/helm/vault.values.yaml
- terraform/vault/override-values.yml.tmpl
> use vault custom image with plugin

- system/vault/helm/argo.yaml
> ignore MutatingWebhookConfiguration cabundle vault

- system/argocd/argocd-cm-health.yaml
- system/argocd/kustomization.yaml
> argocd-cm-health

- system/vault/helm/argo.yaml
> changing targetRevision to master

- system/vault/helm/vault.values.yaml
- terraform/vault/override-values.yml.tmpl
> update vault image version

- apps/samples/grav-demo/base/deployment.yaml
- apps/samples/grav-demo/grav-init/Dockerfile
> grav git-sync with vault

- system/vault/configs/policies.yaml
> no data in kv-system path

- apps/calidum-rotae/base/calidum-rotae-service/deployment.yaml
- Update calidum main service to 1.0.2
- Adds entrypoint command to defined allowed domains
> Calidum-rotae v1.0.2

- terraform/users.tf
This PR adds a new user module for AlexanderPan96 to `users.tf`. Please review the configuration and merge the PR to apply the changes.
> Add new member: AlexanderPan96

- terraform/repos.tf
Ajouter les repertoires suivants a github:
- k8s-base
- k8s-mgmt
- k8s-prod
- k8s-nonprod
> new cluster repos

- terraform/gcp/providers.tf
- terraform/providers.tf
- terraform/repos.tf
- terraform/variables.tf
- added more checks
- configure tfe automagically
> changed cluster repo configs

- terraform/modules/user/main.tf
> removed netdata

- apps/argo-apps/kustomization.yaml
- apps/kubewall/argo.yaml
- apps/kubewall/base/deployment.yaml
- apps/kubewall/base/kustomization.yaml
- apps/kubewall/base/network.yaml
- apps/kubewall/kustomization.yaml
- apps/kubewall/prod/ingress.yaml
- apps/kubewall/prod/kustomization.yaml
Test de deploiement de Kubewall
Je vais check si le namespace et le service se met bien en place sur le cluster cedille-cluster.
- [ x] New feature (non-breaking change which adds functionality)
> Kubewall test

- apps/argo-apps/kustomization.yaml
- apps/dronolab/webApp/argo.yaml
- apps/dronolab/webApp/base/deployment.yaml
- apps/dronolab/webApp/base/kustomization.yaml
- apps/dronolab/webApp/base/network.yaml
- apps/dronolab/webApp/kustomization.yaml
- apps/dronolab/webApp/prod/ingress.yaml
- apps/dronolab/webApp/prod/kustomization.yaml
Here's the deployment configuration files for the Dronolab website.
> webApp dronolab deployment

- apps/kubewall/base/kustomization.yaml
- apps/kubewall/base/permissions.yaml
- apps/kubewall/base/permissionsBinding.yaml
- apps/kubewall/prod/kustomization.yaml
remove ingress and add service account for kubewall namespace in cedille-cluster
> remove ingress and add service account

- apps/kubewall/base/permissionsBinding.yaml
> fix service account

- apps/argo-apps/kustomization.yaml
- apps/crabe/webApp/argo.yaml
- apps/crabe/webApp/base/deployment.yaml
- apps/crabe/webApp/base/kustomization.yaml
- apps/crabe/webApp/base/service.yaml
- apps/crabe/webApp/base/sql/service.yaml
- apps/crabe/webApp/base/sql/statefulset.yaml
- apps/crabe/webApp/kustomization.yaml
- apps/crabe/webApp/prod/ingress.yaml
- apps/crabe/webApp/prod/kustomization.yaml
crabe deployment config file for argoCD
> crabe web deployment

- apps/crabe/webApp/base/deployment.yaml
- apps/crabe/webApp/base/sql/statefulset.yaml
renaming the CRABE secrets variables
> Crabe web app

- apps/crabe/webApp/base/deployment.yaml
> Crabe web app config secrets PT.2

- terraform/users.tf
> Ajout membre justlac
